version: '3.8'
services:
  app:
    image: ${REGISTRY}/dmitriy282/my-app:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://space_admin:supersecret@db:5432/space_logbook
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - 'traefik.http.routers.${ROUTER_NAME}.rule=Host(`${DYNAMIC_HOST}`)'
      - "traefik.http.routers.${ROUTER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTER_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${ROUTER_NAME}.loadbalancer.server.port=5000"
    networks:
      - web
      - traefik-net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
 
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - web
 
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=space_admin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=space_logbook
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U space_admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web
 
networks:
  web:
    driver: bridge
  traefik-net:
    external: true
 
volumes:
  pgdata:
