version: '3.8'

services:
  app:
    image: ${REGISTRY}/dmitriy282/my-app:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://space_admin:supersecret@db:5432/space_logbook
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.app.rule=Host(`${DYNAMIC_HOST}`)'
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=5000"
    networks:
      - web
      - traefik-net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g

  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=dimavk3@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--api.insecure=true"
      # Додайте цей рядок для дебагу, потім приберіть:
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - web

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=space_admin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=space_logbook
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U space_admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:
    driver: bridge
  traefik-net:
    external: true
volumes:
  pgdata:
